export const COOKBOOK_ACTIONS = {
    FETCH_COOKBOOKS: 'FETCH_COOKBOOKS',
    SHOW_COOKBOOKS: 'SHOW_COOKBOOKS',
    POST_COOKBOOKS: 'POST_COOKBOOKS',
    FETCH_CATEGORIES: 'FETCH_CATEGORIES',
    SHOW_CATEGORIES: 'SHOW_CATEGORIES',
    POST_CATEGORIES: 'POST_CATEGORIES',
    FETCH_RECIPES: 'FETCH_RECIPES',
    SHOW_RECIPES: 'SHOW_RECIPES',
    POST_RECIPES: 'POST_RECIPES'
}