export const COOKBOOK_ACTIONS = {
    FETCH_COOKBOOKS: 'FETCH_COOKBOOKS',
    SHOW_COOKBOOKS: 'SHOW_COOKBOOKS',
    POST_COOKBOOK: 'POST_COOKBOOK',
    // UPDATE_COOKBOOK: 'UPDATE_COOKBOOK',
    DELETE_COOKBOOK: 'DELETE_COOKBOOK',

    FETCH_CATEGORIES: 'FETCH_CATEGORIES',
    SHOW_CATEGORIES: 'SHOW_CATEGORIES',
    POST_CATEGORY: 'POST_CATEGORY',
    DELETE_CATEGORY: 'DELETE_CATEGORY',

    FETCH_RECIPES: 'FETCH_RECIPES',
    SHOW_RECIPES: 'SHOW_RECIPES',
    POST_RECIPE: 'POST_RECIPE',
    DELETE_RECIPE: 'DELETE_RECIPE',

    FETCH_USER: 'FETCH_USER',
    SHOW_USER: 'SHOW_USER'
}