export const COOKBOOK_ACTIONS = {
    FETCH_COOKBOOKS: 'FETCH_COOKBOOKS',
    SHOW_COOKBOOKS: 'SHOW_COOKBOOKS',
    POST_COOKBOOK: 'POST_COOKBOOK',
    UPDATE_COOKBOOK: 'UPDATE_COOKBOOK',
    DELETE_COOKBOOK: 'DELETE_COOKBOOK',

    FETCH_CATEGORIES: 'FETCH_CATEGORIES',
    SHOW_CATEGORIES: 'SHOW_CATEGORIES',
    POST_CATEGORY: 'POST_CATEGORY',
    UPDATE_CATEGORY: 'UPDATE_CATEGORY',
    DELETE_CATEGORY: 'DELETE_CATEGORY',

    FETCH_RECIPES: 'FETCH_RECIPES',
    SHOW_RECIPES: 'SHOW_RECIPES',
    POST_RECIPE: 'POST_RECIPE',
    DELETE_RECIPE: 'DELETE_RECIPE',
    UPDATE_RECIPE: 'UPDATE_RECIPE',
    
    LIKE_RECIPE: 'LIKE_RECIPE',
    FETCH_LIKES: 'FETCH_LIKES',
    SHOW_LIKES: 'SHOW_LIKES',
    DELETE_LIKE: 'DELETE_LIKE'
}